# Generated by Django 4.1.6 on 2023-03-28 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registered', '0002_alter_surrendered_lease_options'),
        ('lease_bills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='correction',
        ),
        migrations.AlterModelOptions(
            name='billdata',
            options={'verbose_name': 'Data Store', 'verbose_name_plural': 'Data Store'},
        ),
        migrations.AddField(
            model_name='bill_dataset',
            name='area',
            field=models.DecimalField(decimal_places=2, default=900, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill_dataset',
            name='area_units',
            field=models.CharField(default='m²', max_length=50),
        ),
        migrations.AddField(
            model_name='bill_dataset',
            name='landuse_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registered.landuse_type'),
            preserve_default=False,
        ),
    ]
