# Generated by Django 4.1.6 on 2023-03-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lease_bills', '0003_alter_bill_dataset_data_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdata_landuse',
            name='billdataset_id',
        ),
        migrations.RemoveField(
            model_name='billdata_landuse',
            name='landuse',
        ),
        migrations.AlterModelOptions(
            name='billdata',
            options={'verbose_name': 'Data Bucket', 'verbose_name_plural': 'Data Bucket'},
        ),
        migrations.AlterModelOptions(
            name='billing_period',
            options={'verbose_name': 'Billing Period', 'verbose_name_plural': 'Billing Periods'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='window_period',
            field=models.ForeignKey(limit_choices_to=models.Q(('period_state', 'I')), on_delete=django.db.models.deletion.CASCADE, to='lease_bills.billing_period'),
        ),
        migrations.AlterField(
            model_name='bill_dataset',
            name='data_state',
            field=models.CharField(choices=[('P', 'Pre-commit'), ('C', 'Commit'), ('D', 'Deleted')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='billdata_area',
        ),
        migrations.DeleteModel(
            name='billdata_Landuse',
        ),
    ]
