# Generated by Django 4.1.3 on 2023-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_bills', '0004_bill_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_details',
            name='invoice_number',
            field=models.CharField(max_length=255),
        ),
    ]
