# Generated by Django 4.1.3 on 2023-02-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_bills', '0005_alter_bill_details_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_details',
            name='zone_number',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
    ]
