# Generated by Django 4.1.6 on 2023-03-31 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_bills', '0005_alter_bill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='lease_number',
            field=models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
