"""
Django settings for Billing project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from django.conf.global_settings import LANGUAGES as DJANGO_LANGUAGES
import os


#import keys
#import pytz

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-e!k42$8b3zpgx+5@+i0w3y94-0e9-0&7xpy9n_%@yk28l3(whc'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#with open('billing/etc/secret_key.txt') as f:
#    SECRET_KEY = f.read().strip()
#SECRET
# SECURITY WARNING: don't run with debug turned on in production!

# settings.py

# Configure django-axes


DEBUG = True

SITE_ID = 1

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'laa-hq-hrfm','192.168.0.4','billing.local']


# Billing Settings
CSRF_COOKIE_NAME = 'billing_csrftoken'
SESSION_COOKIE_NAME = 'billing_session_id'
CSRF_COOKIE_PATH = '/'



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'admin_views',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'search_placeholder',
    'mathfilters',
    'import_export',
    'Report',
    'reference_tables',
    'registered',
    'lease_bills.apps.LeaseBillsConfig',
    #'user_accounts.apps.UserAccountsConfig',
    'admin_extra_buttons',
    #'silk',
    #'custom_silk',
    'axes',
    #'debug_toolbar',
]
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = 1  # Lockout for 1 minute if failure limit is reached

MIDDLEWARE = [
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # AxesMiddleware should be the last middleware in the MIDDLEWARE list.
    #'silk.middleware.SilkyMiddleware',
    #'django_cprofile_middleware.middleware.ProfilerMiddleware',
    'axes.middleware.AxesMiddleware', 
    
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',

    # Django ModelBackend is the default authentication backend.
    #'registered.custom_auth_backends.NoPermissionCheckModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

SESSION_COOKIE_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_COOKIE_AGE = 300 #close session after 5 minutes of inactivity

ROOT_URLCONF = 'Billing.urls'

LOGIN_REDIRECT_URL = '/'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

STATIC_ROOT = BASE_DIR / 'productionfiles'

STATIC_URL = '/static/'

# LOGGING = {
    # 'version': 1,
    # 'disable_existing_loggers': False,
    # 'handlers': {
        # 'console': {
            # 'level': 'DEBUG',
            # 'class': 'logging.StreamHandler',
        # },
    # },
    # 'loggers': {
        # 'django.db.backends': {
            # 'handlers': ['console'],
            # 'level': 'DEBUG',
        # },
    # },
# }



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'registered/templates/'),os.path.join(BASE_DIR, 'user_accounts/templates'),os.path.join(BASE_DIR, 'Report/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
            'libraries':{
                'customFilter': 'registered.templatetags.algorithms_tags',
            }
        },
    },
]

TEMPLATE_LOADERS = ('django.template.loaders.app_directories.load_template_source',
)

WSGI_APPLICATION = 'Billing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.postgresql',
        'NAME'    : 'billing',
        'HOST'    : 'localhost',
        'USER'    : 'postgres',
        'PASSWORD': 'admin1234*',
        'PORT'    : '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.UnsaltedSHA1PasswordHasher',
    'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Harare'

USE_I18N = True

USE_TZ = True
INTERNAL_IPS = ('127.0.0.1',)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/




# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Billing Management System",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Billing System",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Billing-System ",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "registered/img/logo_.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "registered/img/logo.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Billing Management System",

    # Copyright on the footer
    "copyright": "Land Administration Authority",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    "search_model": ["auth.User"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        #{"name": "Registered",  "url": "registered.html"},

        # external url that opens in a new window (Permissions can be added)
        #{"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "registered"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        #{"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": False,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['Groups'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["user_accounts","reference_tables","reference_tables.landuse_Type","reference_tables.reference_table", "registered","registered.landuse_type", "registered.lease","registered.lease_details", "registered.surrendered_lease","registered.alter_LandUse","registered.adjusted_area","lease_bills","lease_bills.verification","lease_bills.correction","lease_bills.bill_payment","lease_bills.bill_dataset","lease_bills.bill","lease_bills.bill_invoice","lease_bills.bill_payment","hello"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages", 
            "url": "make_messages", 
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "registered.lease":"fas fa-landmark",
        "registered.lease_details":"fas fa-info-circle",
        "registered.surrendered_lease":"fas fa-ban",
        "registered.adjusted_area":"fas fa-chart-area",
        "registered.alter_LandUse":"fas fa-certificate",
        "reference_tables.landuse_type":"fas fa-check-double",
        "reference_tables.reference_table":"fas fa-table",
        "lease_bills.correction":"	fas fa-edit",
        "lease_bills.verification":"	fas fa-certificate",
        "lease_bills.bill":" fas fa-receipt",
        "lease_bills.bill_invoice":"fas fa-file-invoice",
        "lease_bills": "fas fa-dollar-sign",
        "lease_bills.bill_finale": "fas fa-calendar-alt",
        "lease_bills.bill_dataset": "fas fa-database",
        "lease_bills.billdata": "fas  fa-server",
        "lease_bills.bill_payment": "fas fa-money-bill-wave-alt",
        "reference_tables.billing_period": "fas fa-calendar-day",
        "registered": "fas fa-database",
        "user_accounts":"fas fa-users-cog",
        "user_accounts.user":"fas fa-users",
        "Report":"fas fa-chart-bar",
        "reference_tables":"fas fa-archive"
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": 'registered/css/custom-theme.css',
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    #"language_chooser": True,
}


