# Generated by Django 4.1.3 on 2023-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lastpayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
