# Generated by Django 4.1.6 on 2023-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='correction_state',
            field=models.BooleanField(default=True),
        ),
    ]
