# Generated by Django 4.1.6 on 2023-03-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registered', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surrendered_lease',
            options={'verbose_name': 'Surrender Lease ', 'verbose_name_plural': 'Surrender Leases'},
        ),
    ]
