# Generated by Django 4.1.6 on 2023-03-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registered', '0002_alter_surrendered_lease_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surrendered_lease',
            name='lease_number',
            field=models.OneToOneField(limit_choices_to=models.Q(('lease_status', 'A')), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registered.lease'),
        ),
    ]
