# Generated by Django 4.1.6 on 2023-02-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registered', '0002_alter_lease_lastpayment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjusted_area',
            options={'verbose_name': 'Modify Area', 'verbose_name_plural': 'Modify Areas'},
        ),
        migrations.AlterModelOptions(
            name='alter_landuse',
            options={'verbose_name': 'Change Land use', 'verbose_name_plural': 'Change Land use'},
        ),
        migrations.AlterModelOptions(
            name='landuse_type',
            options={'verbose_name': 'Land use Type', 'verbose_name_plural': 'Land use Types'},
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'verbose_name': 'Lease', 'verbose_name_plural': 'Leases'},
        ),
        migrations.AlterModelOptions(
            name='surrendered_lease',
            options={'verbose_name': 'Surrender Lease', 'verbose_name_plural': 'Surrender Leases'},
        ),
    ]
